spring.application.name=infra
spring.profiles.active=@profiles.active@

server.port=9000
server.shutdown=graceful
spring.threads.virtual.enabled=true

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

mybatis-plus.global-config.db-config.id-type=assign_id
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.configuration.shrink-whitespaces-in-sql=true

logging.level.root=info
logging.level.io.github.yilers=debug
logging.file.path=./log
logging.file.name=${logging.file.path}/${spring.application.name}/app.log

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

permission.column.table=upm_log,upm_user

# token 名称（同时也是 cookie 名称）
sa-token.token-name=Authorization
sa-token.token-prefix=Bearer
sa-token.is-read-cookie=false
sa-token.is-read-body=false
# token 有效期（单位：秒） 默认30天，-1 代表永久有效
sa-token.timeout=172800
sa-token.auto-renew=true
# token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
sa-token.active-timeout=-1
# 动态设置活跃时间
sa-token.dynamic-active-timeout=false
# 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
sa-token.is-concurrent=true
# 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
sa-token.is-share=true
# token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
sa-token.token-style=simple-uuid
# 是否输出操作日志
sa-token.is-log=true

upm.application-code=infra
upm.sso.secret-key=${UPM_SSO_SECRET_KEY:yilers}
upm.sso.ticket-timeout=60

jetcache.statIntervalMinutes=10
jetcache.areaInCacheName=false
jetcache.remote.default.type=redisson
jetcache.remote.default.redissonClient=jetCacheRedisClient
jetcache.remote.default.keyConvertor=jackson
jetcache.remote.default.broadcastChannel=${spring.application.name}
jetcache.remote.default.keyPrefix=jetcache:
jetcache.remote.default.valueEncoder=java
jetcache.remote.default.valueDecoder=java
jetcache.remote.default.defaultExpireInMillis=10000

## jetcache 2.8.x后添加
jetcache.decodeFilterAllowPatterns=io.github.yilers.,com.baomidou.
