<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.yilers</groupId>
        <artifactId>infra-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ai</artifactId>
    <name>infra-ai</name>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>ai-chatbot</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- https://mvnrepository.com/artifact/org.springframework.ai/spring-ai-starter-model-openai -->
        <spring-ai.version>2.0.0</spring-ai.version>
        <spring-ai-alibaba.version>2.0.0-M1.1</spring-ai-alibaba.version>
        <spring-ai-agent-utils.version>0.10.0</spring-ai-agent-utils.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>